name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish ${{ matrix.docs.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docs:
          - target: MonkiProjectsModel
            url: /monki-projects-model
          - target: MonkiMapModel
            url: /monki-map-model
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          base-url: /models/${{ matrix.docs.url }}/swift
          format: html
          inputs: Sources/${{ matrix.docs.target }}
          module-name: ${{ matrix.docs.target }}
          output: Documentation
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.SWIFT_DOC_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Documentation
