name: Swift Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Lint with SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
